### PR TITLE
incomplete loveframes implementation and other stuff

### PR DESCRIPTION
**Pull request by qaisjp**
Implemented loveframes and some other stuff has been done.

### CODE REVIEW

**Comment by josefnpat** [comment]
Take a look at this; https://github.com/UnekPL/loveframes-gray-theme

**Comment by qaisjp** [comment]
this is where i take my 2hr break

**Comment by qaisjp** [comment]
I'm done. I might not be able to code for a while so I'm excited to see how this turns out.

**Comment by josefnpat** [comment]
This is very exciting!

I may cherry pick this, or I might just ask for specific changes before I merge.

I need to review all the code and such later tonight.

**Comment by josefnpat** [comment]
@qaisjp please stop committing to this pull request, you're making it impossible to review and merge.

The best thing you can do is smaller pull requests.

**Comment by josefnpat** [comment]
These commits are incredibly hard to pull apart because of all the restructuring.

**Comment by josefnpat** [comment]
I won't have time to review this until Saturday most likely. Sorry.

**Comment by qaisjp** [comment]
Ok. Ill be busy until then anyway. Ill stop modifying.

**Comment by josefnpat** [comment]
@qaisjp You don't have to stop modifying, you just need to make small merge requests. 

http://stackoverflow.com/questions/8450036/how-to-open-multiple-pull-requests-on-github

**Comment by qaisjp** [comment]
I meant ill top modifying my master. I fid t better to just jump in to the code and see what I can do. The issue with new pull requests is that either old code would be deprecated or other code would be invalid. Ill try and do this, though.

**Comment by qaisjp** [comment]
Sorry :(

**Comment by josefnpat** [comment]
Don't delete this branch, I can merge the code via cherry-picking :) I don't want all the good work you've done go to waste.

Just for future reference, try to keep your merge requests small and to the point.

**Comment by qaisjp** [comment]
ok :)

**Comment by josefnpat** [comment]
I went through this, and it's all over the place. This is an incredibly dirty and confusing pull request. I went through allt he code, and in order of each commit, this is the log;

```
added love frames submodule
changed draw to be dependant on prior icons
renamed lib to vendor & updated lib locations
incorperated loveframes api hooks
moved love.update to event/init
commented out row drawing
added loveframes hooks to events/init
commented out select index system
changed init into a module with locallized functions that don't pertain
set the height of the mode to a fixed size
updating panel colors in new display/event/init system
using alternate module loading instead of .load()
removed loveframes submodule
renamed loveframes lib from frames to loveframes
removed other half of submodule system
added loveframes skin
renamed loveframes lib from loveframes to frames
added loveframes lib
modified loveframes orange skin
added favorite icon system
```

Considering the new direction of #70, I'm going to close this merge request.

Next time, please make your merge requests small and concise, and ask before doing architectural changes.

It's a lot easier to merge 20 small requests than 1 big complicated one. I don't mind merging smaller ones by hand.

Also, don't comment stuff out, just delete it. We're using a distributed revision control system for a reason.

**Pull request closed without merging**
