### PR TITLE
Added Games: Matt and Chris, Left Right Pong and Who Wants the Money

### PR DESCRIPTION
**Pull request by HyperNexus**

### CODE REVIEW

**Comment by qaisjp** [comment]
:+1:

**Comment by josefnpat** [comment]
@HyperNexus Thank you so much for the merge request! It's fantastic that you want to get these games into vapor!

There are a few issues. **The first is technical;** you have used md5sums instead of sha1sums for the hashes. The games won't validate, because the sha1sum doesn't match your md5sum. Please check the footnote [1] on the index on how to find the sha1 hash.

The others are entirely subjective; **All of these issues are minor, and won't stop me from accepting this merge request when the sha1sum's are corrected.**

**Left Right Pong** &mdash; I have no problem with this game. It's a game, it's playable and entirely accessible.

**Matt and Chris** &mdash; This game is technically unplayable **when a dongle is being used**.

```
useKeyboard = Controller.getNumberConnected() < 2
```

While my system has only one controller connected, it reads it has four because it attaches the controller via a dongle, thus providing three phantom dongles.

Providing a way for the player to manually switch the controller scheme would be very helpful (e.G."Press M to switch between Keyboard and Controller Layout.") Not that much to complain about, honestly.

**Who Wants the Money** &mdash; again, this game suffers from the phantom controllers issue via a dongle. Also, this game is rather confusing due to the fact that none of the controls are explained. it took me a bit to realize that player one was z-x-space instead of wasd.

**Comment by HyperNexus** [comment]
Sorry about that. I'll go through and fix these things up when I get the chance.

**Comment by HyperNexus** [comment]
Okay fixed. When running fciv I accidentally copied the md5 hashes instead of the sha1 ones.

I've uploaded new versions of both Matt and Chris and You Want the Money. They both allow you to change the control mode to keyboard/controller on the fly. You Want the Money now has an instructions screen.

My understanding is that the phantom controller issue is just one with SDL and the 360 wireless controller on Linux. So I haven't fixed that.

**Comment by josefnpat** [comment]
@HyperNexus 

I just copied the part of the json instead of merging - sorry, a bit lazy!

Great job, works fantastically!

**Pull request closed without merging**
