### PR TITLE
Added Grand Health Auto

### PR DESCRIPTION
**Pull request by martinfelis**
Hope it works!

### CODE REVIEW

**Comment by josefnpat** [comment]
Thanks!

**Comment by josefnpat** [comment]
I had to remove one sentence so it would fit in the current UI. If that is an issue, please feel free to change it.

You can test it by removing the games.json in your local `love/vapor-data/` folder, and running the .love with the `force_local` flag: `love vapor-*.love force_local`

**Comment by martinfelis** [comment]
Absolutely fine. I really like vapor! Good work!

**Comment by josefnpat** [comment]
@martinfelis Thanks!

**Pull request merged**
