### PR TITLE
Hopefully Updated Vapor to love 0.9.2

### PR DESCRIPTION
**Pull request by Bobbyjoness**
Please test and give feed back. Next is the compatibility layer

### CODE REVIEW

**Comment by Bobbyjoness** [comment]
When can this be accepted?

**Comment by josefnpat** [comment]
When the compatibility layer is ready.

**Comment by Bobbyjoness** [comment]
Ok its taking longer then I thought. Is it ok if its not 100% compatibility?

**Comment by josefnpat** [comment]
@Bobbyjoness Optimally, it should at least cover all of the games that work in vapor already.

**Comment by Bobbyjoness** [comment]
Ok. Certain APIs may not be able to be mimicked properly. The one that may give the most problems is threads. And I haven't tackled particle systems yet.

**Comment by Bobbyjoness** [comment]
Woah I was denied ? :( lol

**Comment by josefnpat** [comment]
@Bobbyjoness sorry, looks like github auto-closed it. You will have to offer a pull request against the `vapor0.x` branch, now that `master` is closed.

**Pull request closed without merging**
