### PR TITLE
Download button is hidden when opening Vapor

### PR DESCRIPTION
**Pull request by Yonaba**
Hi,

Adding this single line makes the download button hidden (and unavailable) when opening Vapor.
As such, only the description "Welcome to Vapor" is visible.
The button becomes visible when the user clicks on any game in the list.

Regards,
Roland.

### CODE REVIEW

**Comment by josefnpat** [comment]
I didn't realize it was so easy to hide buttons in LoveFrames!

Thanks!

**Comment by Yonaba** [comment]
Actually, it was quite like a hack. Or maybe @nikolairesokav completely forgot to add a `(get/set)Visible()` method to  [LoveFrames](https://github.com/NikolaiResokav/LoveFrames) [button class API](https://github.com/NikolaiResokav/LoveFrames/blob/master/objects/button.lua). I was expecting such a method, but I couldn't find it, then I decided to alter the `visible` property of the download button.

**Comment by josefnpat** [comment]
Ah!

While :SetVisible is not in the button docs, it is in the base docs:

http://nikolairesokav.com/projects/loveframes/docs/objects/base

Will push a working change momentarily.

**Comment by Yonaba** [comment]
Ah...Silly me. Of course, the Button object inherits from the Base object, which already implements (get/set)Visible...

**Pull request merged**
